site_name: M81's Website
site_description: C++ projects, computer science insights, and amateur radio adventures by a CS undergraduate.
site_url: https://zzhx2006.github.io
repo_url: https://github.com/zzhx2006
repo_name: zzhx2006

theme:
  name: material
  language: en
  logo: assets/messier81.png
  favicon: assets/messier81.png
  features:
    - navigation.indexes
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
  font:
    text: "Times New Roman\",\"SimSun\",\"Noto Sans SC\",\"serif"
    code: "Google Sans Code\",\"JetBrains Mono\",\"Consolas\",\"NSimSun\",\"monospace"
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-3
        name: Switch to light mode

nav:
  - Home: index.md
  - Blogs:
      - blog/index.md
  - About:
      - about/index.md

plugins:
  - search
  - blog:
      blog_toc: true
      archive: true
      archive_date_format: yyyy/MM
      archive_url_date_format: yyyy/MM
      archive_url_format: "{date}"
      post_url_date_format: yyyy/MM
      post_url_format: "{slug}"
      post_readtime: false
      authors: false
extra:
  social:
    - icon: simple/github
      link: https://github.com/zzhx2006
    - icon: material/email
      link: mailto:zzhx2006@outlook.com
      name: outlook.com
    - icon: simple/bilibili
      link: https://space.bilibili.com/1805605010
    - icon: fontawesome/brands/weibo
      link: https://weibo.com/u/6237206866
    - icon: simple/zhihu
      link: https://www.zhihu.com/people/xuan-xuan-42-18-81
    - icon: material/arch
      link: https://wiki.archlinuxcn.org/wiki/User:Messier81

extra_css:
  - assets/stylesheets/extra.css

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption

copyright: Copyright &copy; 2024-2025 Zhanhaoxiang Zhang
