site_name: M81 的个人网站
site_description: 个人 GitHub Page 网站，记录零碎日常学习
site_url: https://zzhx2006.github.io
repo_url: https://github.com/zzhx2006/zzhx2006.github.io
repo_name: zzhx2006.github.io

theme:
  name: material
  language: zh
  logo: assets/logo/my-logo.png
  favicon: assets/logo/my-logo.png
  features:
    - navigation.indexes
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy # 代码块右上角的复制按钮
    # - content.code.annotate # 一个“+”的代码注释
  font:
    text: stzhongsong
    code: JetBrains Mono
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: 切换到深色模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: blue
      toggle:
        icon: material/weather-night
        name: 切换到浅色模式

nav:
  - 主页: index.md
  - 博客:
      - blog/index.md

plugins:
  - search
  - blog:
      blog_toc: true
      archive_date_format: yyyy 年 MM 月
      archive_url_date_format: yyyy/MM
      archive_url_format: "{date}"
      post_url_date_format: yyyy/MM
extra:
  social:
    - icon: simple/github
      link: https://github.com/zzhx2006
    - icon: material/email
      link: mailto:zzhx2006@outlook.com
      name: outlook.com
    - icon: simple/bilibili
      link: https://space.bilibili.com/1805605010
    - icon: fontawesome/brands/weibo
      link: https://weibo.com/u/6237206866
    - icon: simple/zhihu
      link: https://www.zhihu.com/people/xuan-xuan-42-18-81
    - icon: material/arch
      link: https://wiki.archlinuxcn.org/wiki/User:Messier81

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

copyright: Copyright &copy; 2024 Zhanhaoxiang Zhang
